# Site settings
title: Sense of Tech
description: >
  AI-assisted engineering, custom application development and application
  modernization. Ingénierie assistée par IA, création et modernisation
  d'applications.
baseurl: ""
url: "https://www.senseof.tech"
twitter_username: senseof_tech
github_username: senseoftech
# email: info@senseof.tech

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

incremental: true

exclude:
  - Gemfile
  - Gemfile.lock
